/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductDetailRouteImport } from './routes/productDetail'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/Checkout'
import { Route as IndexRouteImport } from './routes/index'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductDetailRoute = ProductDetailRouteImport.update({
  id: '/productDetail',
  path: '/productDetail',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/Checkout',
  path: '/Checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Checkout': typeof CheckoutRoute
  '/cart': typeof CartRoute
  '/productDetail': typeof ProductDetailRoute
  '/products': typeof ProductsRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Checkout': typeof CheckoutRoute
  '/cart': typeof CartRoute
  '/productDetail': typeof ProductDetailRoute
  '/products': typeof ProductsRoute
  '/success': typeof SuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Checkout': typeof CheckoutRoute
  '/cart': typeof CartRoute
  '/productDetail': typeof ProductDetailRoute
  '/products': typeof ProductsRoute
  '/success': typeof SuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Checkout'
    | '/cart'
    | '/productDetail'
    | '/products'
    | '/success'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Checkout' | '/cart' | '/productDetail' | '/products' | '/success'
  id:
    | '__root__'
    | '/'
    | '/Checkout'
    | '/cart'
    | '/productDetail'
    | '/products'
    | '/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  CartRoute: typeof CartRoute
  ProductDetailRoute: typeof ProductDetailRoute
  ProductsRoute: typeof ProductsRoute
  SuccessRoute: typeof SuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productDetail': {
      id: '/productDetail'
      path: '/productDetail'
      fullPath: '/productDetail'
      preLoaderRoute: typeof ProductDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Checkout': {
      id: '/Checkout'
      path: '/Checkout'
      fullPath: '/Checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  CartRoute: CartRoute,
  ProductDetailRoute: ProductDetailRoute,
  ProductsRoute: ProductsRoute,
  SuccessRoute: SuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
